server:
  port: 8090
  error:
    include-stacktrace: never
  
spring:
  application:
    name: mscv-Cosechador
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ArandanosT
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform : org.hibernate.dialect.MySQLDialect
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka